type CityItem = {
  value: string;
  label: string;
};

const cities: Array<CityItem> = [
  {
    value: "Aleksandrów Kujawski",
    label: "Aleksandrów Kujawski, pow. aleksandrowski",
  },
  { value: "Ciechocinek", label: "Ciechocinek, pow. aleksandrowski" },
  { value: "Nieszawa", label: "Nieszawa, pow. aleksandrowski" },
  { value: "Augustów", label: "Augustów, pow. augustowski" },
  { value: "Lipsk", label: "Lipsk, pow. augustowski" },
  { value: "Bartoszyce", label: "Bartoszyce, pow. bartoszycki" },
  { value: "Bisztynek", label: "Bisztynek, pow. bartoszycki" },
  { value: "Górowo Iławeckie", label: "Górowo Iławeckie, pow. bartoszycki" },
  { value: "Sępopol", label: "Sępopol, pow. bartoszycki" },
  { value: "Bełchatów", label: "Bełchatów, pow. bełchatowski" },
  { value: "Zelów", label: "Zelów, pow. bełchatowski" },
  { value: "Będzin", label: "Będzin, pow. będziński" },
  { value: "Czeladź", label: "Czeladź, pow. będziński" },
  { value: "Siewierz", label: "Siewierz, pow. będziński" },
  { value: "Sławków", label: "Sławków, pow. będziński" },
  { value: "Wojkowice", label: "Wojkowice, pow. będziński" },
  { value: "Międzyrzec Podlaski", label: "Międzyrzec Podlaski, pow. bialski" },
  { value: "Terespol", label: "Terespol, pow. bialski" },
  { value: "Biała Podlaska", label: "Biała Podlaska" },
  { value: "Białobrzegi", label: "Białobrzegi, pow. białobrzeski" },
  { value: "Wyśmierzyce", label: "Wyśmierzyce, pow. białobrzeski" },
  { value: "Białogard", label: "Białogard, pow. białogardzki" },
  { value: "Karlino", label: "Karlino, pow. białogardzki" },
  { value: "Tychowo", label: "Tychowo, pow. białogardzki" },
  { value: "Choroszcz", label: "Choroszcz, pow. białostocki" },
  {
    value: "Czarna Białostocka",
    label: "Czarna Białostocka, pow. białostocki",
  },
  { value: "Łapy", label: "Łapy, pow. białostocki" },
  { value: "Michałowo", label: "Michałowo, pow. białostocki" },
  { value: "Supraśl", label: "Supraśl, pow. białostocki" },
  { value: "Suraż", label: "Suraż, pow. białostocki" },
  { value: "Tykocin", label: "Tykocin, pow. białostocki" },
  { value: "Wasilków", label: "Wasilków, pow. białostocki" },
  { value: "Zabłudów", label: "Zabłudów, pow. białostocki" },
  { value: "Białystok", label: "Białystok" },
  { value: "Bielsk Podlaski", label: "Bielsk Podlaski, pow. bielski" },
  { value: "Brańsk", label: "Brańsk, pow. bielski" },
  {
    value: "Czechowice-Dziedzice",
    label: "Czechowice-Dziedzice, pow. bielski",
  },
  { value: "Szczyrk", label: "Szczyrk, pow. bielski" },
  { value: "Wilamowice", label: "Wilamowice, pow. bielski" },
  { value: "Bielsko-Biała", label: "Bielsko-Biała" },
  { value: "Bieruń", label: "Bieruń, pow. bieruńsko-lędziński" },
  { value: "Imielin", label: "Imielin, pow. bieruńsko-lędziński" },
  { value: "Lędziny", label: "Lędziny, pow. bieruńsko-lędziński" },
  { value: "Ustrzyki Dolne", label: "Ustrzyki Dolne, pow. bieszczadzki" },
  { value: "Biłgoraj", label: "Biłgoraj, pow. biłgorajski" },
  { value: "Frampol", label: "Frampol, pow. biłgorajski" },
  { value: "Goraj", label: "Goraj, pow. biłgorajski" },
  { value: "Józefów", label: "Józefów, pow. biłgorajski" },
  { value: "Tarnogród", label: "Tarnogród, pow. biłgorajski" },
  { value: "Bochnia", label: "Bochnia, pow. bocheński" },
  { value: "Nowy Wiśnicz", label: "Nowy Wiśnicz, pow. bocheński" },
  { value: "Bolesławiec", label: "Bolesławiec, pow. bolesławiecki" },
  { value: "Nowogrodziec", label: "Nowogrodziec, pow. bolesławiecki" },
  { value: "Braniewo", label: "Braniewo, pow. braniewski" },
  { value: "Frombork", label: "Frombork, pow. braniewski" },
  { value: "Pieniężno", label: "Pieniężno, pow. braniewski" },
  { value: "Brodnica", label: "Brodnica, pow. brodnicki" },
  { value: "Górzno", label: "Górzno, pow. brodnicki" },
  {
    value: "Jabłonowo Pomorskie",
    label: "Jabłonowo Pomorskie, pow. brodnicki",
  },
  { value: "Brzeg", label: "Brzeg, pow. brzeski" },
  { value: "Brzesko", label: "Brzesko, pow. brzeski" },
  { value: "Czchów", label: "Czchów, pow. brzeski" },
  { value: "Grodków", label: "Grodków, pow. brzeski" },
  { value: "Lewin Brzeski", label: "Lewin Brzeski, pow. brzeski" },
  { value: "Brzeziny", label: "Brzeziny, pow. brzeziński" },
  { value: "Jeżów", label: "Jeżów, pow. brzeziński" },
  { value: "Brzozów", label: "Brzozów, pow. brzozowski" },
  { value: "Busko-Zdrój", label: "Busko-Zdrój, pow. buski" },
  { value: "Nowy Korczyn", label: "Nowy Korczyn, pow. buski" },
  { value: "Pacanów", label: "Pacanów, pow. buski" },
  { value: "Stopnica", label: "Stopnica, pow. buski" },
  { value: "Wiślica", label: "Wiślica, pow. buski" },
  { value: "Koronowo", label: "Koronowo, pow. bydgoski" },
  { value: "Solec Kujawski", label: "Solec Kujawski, pow. bydgoski" },
  { value: "Bydgoszcz", label: "Bydgoszcz" },
  { value: "Bytom", label: "Bytom" },
  { value: "Bytów", label: "Bytów, pow. bytowski" },
  { value: "Miastko", label: "Miastko, pow. bytowski" },
  { value: "Chełm", label: "Chełm" },
  { value: "Chełmno", label: "Chełmno, pow. chełmiński" },
  { value: "Rejowiec", label: "Rejowiec, pow. chełmski" },
  { value: "Rejowiec Fabryczny", label: "Rejowiec Fabryczny, pow. chełmski" },
  { value: "Siedliszcze", label: "Siedliszcze, pow. chełmski" },
  { value: "Budzyń", label: "Budzyń, pow. chodzieski" },
  { value: "Chodzież", label: "Chodzież, pow. chodzieski" },
  { value: "Margonin", label: "Margonin, pow. chodzieski" },
  { value: "Szamocin", label: "Szamocin, pow. chodzieski" },
  { value: "Brusy", label: "Brusy, pow. chojnicki" },
  { value: "Chojnice", label: "Chojnice, pow. chojnicki" },
  { value: "Czersk", label: "Czersk, pow. chojnicki" },
  { value: "Chorzów", label: "Chorzów" },
  { value: "Choszczno", label: "Choszczno, pow. choszczeński" },
  { value: "Drawno", label: "Drawno, pow. choszczeński" },
  { value: "Pełczyce", label: "Pełczyce, pow. choszczeński" },
  { value: "Recz", label: "Recz, pow. choszczeński" },
  { value: "Alwernia", label: "Alwernia, pow. chrzanowski" },
  { value: "Chrzanów", label: "Chrzanów, pow. chrzanowski" },
  { value: "Libiąż", label: "Libiąż, pow. chrzanowski" },
  { value: "Trzebinia", label: "Trzebinia, pow. chrzanowski" },
  { value: "Ciechanów", label: "Ciechanów, pow. ciechanowski" },
  { value: "Glinojeck", label: "Glinojeck, pow. ciechanowski" },
  { value: "Cieszyn", label: "Cieszyn, pow. cieszyński" },
  { value: "Skoczów", label: "Skoczów, pow. cieszyński" },
  { value: "Strumień", label: "Strumień, pow. cieszyński" },
  { value: "Ustroń", label: "Ustroń, pow. cieszyński" },
  { value: "Wisła", label: "Wisła, pow. cieszyński" },
  { value: "Czarnków", label: "Czarnków, pow. czarnkowsko-trzcianecki" },
  {
    value: "Krzyż Wielkopolski",
    label: "Krzyż Wielkopolski, pow. czarnkowsko-trzcianecki",
  },
  { value: "Trzcianka", label: "Trzcianka, pow. czarnkowsko-trzcianecki" },
  { value: "Wieleń", label: "Wieleń, pow. czarnkowsko-trzcianecki" },
  { value: "Częstochowa", label: "Częstochowa" },
  { value: "Blachownia", label: "Blachownia, pow. częstochowski" },
  { value: "Koniecpol", label: "Koniecpol, pow. częstochowski" },
  { value: "Olsztyn", label: "Olsztyn, pow. częstochowski" },
  { value: "Czarne", label: "Czarne, pow. człuchowski" },
  { value: "Człuchów", label: "Człuchów, pow. człuchowski" },
  { value: "Debrzno", label: "Debrzno, pow. człuchowski" },
  { value: "Dąbrowa Górnicza", label: "Dąbrowa Górnicza" },
  { value: "Dąbrowa Tarnowska", label: "Dąbrowa Tarnowska, pow. dąbrowski" },
  { value: "Szczucin", label: "Szczucin, pow. dąbrowski" },
  { value: "Brzostek", label: "Brzostek, pow. dębicki" },
  { value: "Dębica", label: "Dębica, pow. dębicki" },
  { value: "Pilzno", label: "Pilzno, pow. dębicki" },
  { value: "Czaplinek", label: "Czaplinek, pow. drawski" },
  { value: "Drawsko Pomorskie", label: "Drawsko Pomorskie, pow. drawski" },
  { value: "Kalisz Pomorski", label: "Kalisz Pomorski, pow. drawski" },
  { value: "Złocieniec", label: "Złocieniec, pow. drawski" },
  { value: "Działdowo", label: "Działdowo, pow. działdowski" },
  { value: "Lidzbark", label: "Lidzbark, pow. działdowski" },
  { value: "Bielawa", label: "Bielawa, pow. dzierżoniowski" },
  { value: "Dzierżoniów", label: "Dzierżoniów, pow. dzierżoniowski" },
  { value: "Niemcza", label: "Niemcza, pow. dzierżoniowski" },
  { value: "Pieszyce", label: "Pieszyce, pow. dzierżoniowski" },
  { value: "Piława Górna", label: "Piława Górna, pow. dzierżoniowski" },
  { value: "Elbląg", label: "Elbląg" },
  { value: "Młynary", label: "Młynary, pow. elbląski" },
  { value: "Pasłęk", label: "Pasłęk, pow. elbląski" },
  { value: "Tolkmicko", label: "Tolkmicko, pow. elbląski" },
  { value: "Ełk", label: "Ełk, pow. ełcki" },
  { value: "Garwolin", label: "Garwolin, pow. garwoliński" },
  { value: "Łaskarzew", label: "Łaskarzew, pow. garwoliński" },
  { value: "Pilawa", label: "Pilawa, pow. garwoliński" },
  { value: "Żelechów", label: "Żelechów, pow. garwoliński" },
  { value: "Gdańsk", label: "Gdańsk" },
  { value: "Pruszcz Gdański", label: "Pruszcz Gdański, pow. gdański" },
  { value: "Gdynia", label: "Gdynia" },
  { value: "Giżycko", label: "Giżycko, pow. giżycki" },
  { value: "Ryn", label: "Ryn, pow. giżycki" },
  { value: "Gliwice", label: "Gliwice" },
  { value: "Knurów", label: "Knurów, pow. gliwicki" },
  { value: "Pyskowice", label: "Pyskowice, pow. gliwicki" },
  { value: "Sośnicowice", label: "Sośnicowice, pow. gliwicki" },
  { value: "Toszek", label: "Toszek, pow. gliwicki" },
  { value: "Głogów", label: "Głogów, pow. głogowski" },
  { value: "Baborów", label: "Baborów, pow. głubczycki" },
  { value: "Głubczyce", label: "Głubczyce, pow. głubczycki" },
  { value: "Kietrz", label: "Kietrz, pow. głubczycki" },
  { value: "Czerniejewo", label: "Czerniejewo, pow. gnieźnieński" },
  { value: "Gniezno", label: "Gniezno, pow. gnieźnieński" },
  { value: "Kłecko", label: "Kłecko, pow. gnieźnieński" },
  { value: "Trzemeszno", label: "Trzemeszno, pow. gnieźnieński" },
  { value: "Witkowo", label: "Witkowo, pow. gnieźnieński" },
  { value: "Goleniów", label: "Goleniów, pow. goleniowski" },
  { value: "Maszewo", label: "Maszewo, pow. goleniowski" },
  { value: "Nowogard", label: "Nowogard, pow. goleniowski" },
  { value: "Stepnica", label: "Stepnica, pow. goleniowski" },
  { value: "Golub-Dobrzyń", label: "Golub-Dobrzyń, pow. golubsko-dobrzyński" },
  {
    value: "Kowalewo Pomorskie",
    label: "Kowalewo Pomorskie, pow. golubsko-dobrzyński",
  },
  { value: "Gołdap", label: "Gołdap, pow. gołdapski" },
  { value: "Biecz", label: "Biecz, pow. gorlicki" },
  { value: "Bobowa", label: "Bobowa, pow. gorlicki" },
  { value: "Gorlice", label: "Gorlice, pow. gorlicki" },
  { value: "Kostrzyn nad Odrą", label: "Kostrzyn nad Odrą, pow. gorzowski" },
  { value: "Witnica", label: "Witnica, pow. gorzowski" },
  { value: "Gorzów Wielkopolski", label: "Gorzów Wielkopolski" },
  { value: "Gostynin", label: "Gostynin, pow. gostyniński" },
  { value: "Sanniki", label: "Sanniki, pow. gostyniński" },
  { value: "Borek Wielkopolski", label: "Borek Wielkopolski, pow. gostyński" },
  { value: "Gostyń", label: "Gostyń, pow. gostyński" },
  { value: "Krobia", label: "Krobia, pow. gostyński" },
  { value: "Pogorzela", label: "Pogorzela, pow. gostyński" },
  { value: "Poniec", label: "Poniec, pow. gostyński" },
  { value: "Góra", label: "Góra, pow. górowski" },
  { value: "Wąsosz", label: "Wąsosz, pow. górowski" },
  { value: "Grajewo", label: "Grajewo, pow. grajewski" },
  { value: "Rajgród", label: "Rajgród, pow. grajewski" },
  { value: "Szczuczyn", label: "Szczuczyn, pow. grajewski" },
  {
    value: "Grodzisk Mazowiecki",
    label: "Grodzisk Mazowiecki, pow. grodziski",
  },
  {
    value: "Grodzisk Wielkopolski",
    label: "Grodzisk Wielkopolski, pow. grodziski",
  },
  { value: "Milanówek", label: "Milanówek, pow. grodziski" },
  { value: "Podkowa Leśna", label: "Podkowa Leśna, pow. grodziski" },
  { value: "Rakoniewice", label: "Rakoniewice, pow. grodziski" },
  { value: "Wielichowo", label: "Wielichowo, pow. grodziski" },
  { value: "Grójec", label: "Grójec, pow. grójecki" },
  { value: "Mogielnica", label: "Mogielnica, pow. grójecki" },
  {
    value: "Nowe Miasto nad Pilicą",
    label: "Nowe Miasto nad Pilicą, pow. grójecki",
  },
  { value: "Warka", label: "Warka, pow. grójecki" },
  { value: "Grudziądz", label: "Grudziądz" },
  { value: "Łasin", label: "Łasin, pow. grudziądzki" },
  { value: "Radzyń Chełmiński", label: "Radzyń Chełmiński, pow. grudziądzki" },
  { value: "Gryfice", label: "Gryfice, pow. gryficki" },
  { value: "Płoty", label: "Płoty, pow. gryficki" },
  { value: "Trzebiatów", label: "Trzebiatów, pow. gryficki" },
  { value: "Cedynia", label: "Cedynia, pow. gryfiński" },
  { value: "Chojna", label: "Chojna, pow. gryfiński" },
  { value: "Gryfino", label: "Gryfino, pow. gryfiński" },
  { value: "Mieszkowice", label: "Mieszkowice, pow. gryfiński" },
  { value: "Moryń", label: "Moryń, pow. gryfiński" },
  { value: "Trzcińsko-Zdrój", label: "Trzcińsko-Zdrój, pow. gryfiński" },
  { value: "Hajnówka", label: "Hajnówka, pow. hajnowski" },
  { value: "Kleszczele", label: "Kleszczele, pow. hajnowski" },
  { value: "Hrubieszów", label: "Hrubieszów, pow. hrubieszowski" },
  { value: "Iława", label: "Iława, pow. iławski" },
  { value: "Kisielice", label: "Kisielice, pow. iławski" },
  { value: "Lubawa", label: "Lubawa, pow. iławski" },
  { value: "Susz", label: "Susz, pow. iławski" },
  { value: "Zalewo", label: "Zalewo, pow. iławski" },
  { value: "Gniewkowo", label: "Gniewkowo, pow. inowrocławski" },
  { value: "Inowrocław", label: "Inowrocław, pow. inowrocławski" },
  { value: "Janikowo", label: "Janikowo, pow. inowrocławski" },
  { value: "Kruszwica", label: "Kruszwica, pow. inowrocławski" },
  { value: "Pakość", label: "Pakość, pow. inowrocławski" },
  { value: "Janów Lubelski", label: "Janów Lubelski, pow. janowski" },
  { value: "Modliborzyce", label: "Modliborzyce, pow. janowski" },
  { value: "Jaraczewo", label: "Jaraczewo, pow. jarociński" },
  { value: "Jarocin", label: "Jarocin, pow. jarociński" },
  { value: "Żerków", label: "Żerków, pow. jarociński" },
  { value: "Jarosław", label: "Jarosław, pow. jarosławski" },
  { value: "Pruchnik", label: "Pruchnik, pow. jarosławski" },
  { value: "Radymno", label: "Radymno, pow. jarosławski" },
  { value: "Jasło", label: "Jasło, pow. jasielski" },
  { value: "Kołaczyce", label: "Kołaczyce, pow. jasielski" },
  { value: "Jastrzębie-Zdrój", label: "Jastrzębie-Zdrój" },
  { value: "Bolków", label: "Bolków, pow. jaworski" },
  { value: "Jawor", label: "Jawor, pow. jaworski" },
  { value: "Jaworzno", label: "Jaworzno" },
  { value: "Jelenia Góra", label: "Jelenia Góra" },
  { value: "Jędrzejów", label: "Jędrzejów, pow. jędrzejowski" },
  { value: "Małogoszcz", label: "Małogoszcz, pow. jędrzejowski" },
  { value: "Sędziszów", label: "Sędziszów, pow. jędrzejowski" },
  { value: "Wodzisław", label: "Wodzisław, pow. jędrzejowski" },
  { value: "Koźminek", label: "Koźminek, pow. kaliski" },
  { value: "Opatówek", label: "Opatówek, pow. kaliski" },
  { value: "Stawiszyn", label: "Stawiszyn, pow. kaliski" },
  { value: "Kalisz", label: "Kalisz" },
  { value: "Kamienna Góra", label: "Kamienna Góra, pow. kamiennogórski" },
  { value: "Lubawka", label: "Lubawka, pow. kamiennogórski" },
  { value: "Dziwnów", label: "Dziwnów, pow. kamieński" },
  { value: "Golczewo", label: "Golczewo, pow. kamieński" },
  { value: "Kamień Pomorski", label: "Kamień Pomorski, pow. kamieński" },
  { value: "Międzyzdroje", label: "Międzyzdroje, pow. kamieński" },
  { value: "Wolin", label: "Wolin, pow. kamieński" },
  { value: "Karpacz", label: "Karpacz, pow. karkonoski" },
  { value: "Kowary", label: "Kowary, pow. karkonoski" },
  { value: "Piechowice", label: "Piechowice, pow. karkonoski" },
  { value: "Szklarska Poręba", label: "Szklarska Poręba, pow. karkonoski" },
  { value: "Kartuzy", label: "Kartuzy, pow. kartuski" },
  { value: "Żukowo", label: "Żukowo, pow. kartuski" },
  { value: "Katowice", label: "Katowice" },
  { value: "Kazimierza Wielka", label: "Kazimierza Wielka, pow. kazimierski" },
  { value: "Opatowiec", label: "Opatowiec, pow. kazimierski" },
  { value: "Skalbmierz", label: "Skalbmierz, pow. kazimierski" },
  {
    value: "Kędzierzyn-Koźle",
    label: "Kędzierzyn-Koźle, pow. kędzierzyńsko-kozielski",
  },
  { value: "Kępno", label: "Kępno, pow. kępiński" },
  { value: "Kętrzyn", label: "Kętrzyn, pow. kętrzyński" },
  { value: "Korsze", label: "Korsze, pow. kętrzyński" },
  { value: "Reszel", label: "Reszel, pow. kętrzyński" },
  { value: "Kielce", label: "Kielce" },
  { value: "Bodzentyn", label: "Bodzentyn, pow. kielecki" },
  { value: "Chęciny", label: "Chęciny, pow. kielecki" },
  { value: "Chmielnik", label: "Chmielnik, pow. kielecki" },
  { value: "Daleszyce", label: "Daleszyce, pow. kielecki" },
  { value: "Łagów", label: "Łagów, pow. kielecki" },
  { value: "Łopuszno", label: "Łopuszno, pow. kielecki" },
  { value: "Morawica", label: "Morawica, pow. kielecki" },
  { value: "Nowa Słupia", label: "Nowa Słupia, pow. kielecki" },
  { value: "Piekoszów", label: "Piekoszów, pow. kielecki" },
  { value: "Pierzchnica", label: "Pierzchnica, pow. kielecki" },
  { value: "Byczyna", label: "Byczyna, pow. kluczborski" },
  { value: "Kluczbork", label: "Kluczbork, pow. kluczborski" },
  { value: "Wołczyn", label: "Wołczyn, pow. kluczborski" },
  { value: "Kłobuck", label: "Kłobuck, pow. kłobucki" },
  { value: "Krzepice", label: "Krzepice, pow. kłobucki" },
  { value: "Bystrzyca Kłodzka", label: "Bystrzyca Kłodzka, pow. kłodzki" },
  { value: "Duszniki-Zdrój", label: "Duszniki-Zdrój, pow. kłodzki" },
  { value: "Kłodzko", label: "Kłodzko, pow. kłodzki" },
  { value: "Kudowa-Zdrój", label: "Kudowa-Zdrój, pow. kłodzki" },
  { value: "Lądek-Zdrój", label: "Lądek-Zdrój, pow. kłodzki" },
  { value: "Międzylesie", label: "Międzylesie, pow. kłodzki" },
  { value: "Nowa Ruda", label: "Nowa Ruda, pow. kłodzki" },
  { value: "Polanica-Zdrój", label: "Polanica-Zdrój, pow. kłodzki" },
  { value: "Radków", label: "Radków, pow. kłodzki" },
  { value: "Stronie Śląskie", label: "Stronie Śląskie, pow. kłodzki" },
  { value: "Szczytna", label: "Szczytna, pow. kłodzki" },
  { value: "Kolbuszowa", label: "Kolbuszowa, pow. kolbuszowski" },
  { value: "Kolno", label: "Kolno, pow. kolneński" },
  { value: "Stawiski", label: "Stawiski, pow. kolneński" },
  { value: "Dąbie", label: "Dąbie, pow. kolski" },
  { value: "Kłodawa", label: "Kłodawa, pow. kolski" },
  { value: "Koło", label: "Koło, pow. kolski" },
  { value: "Przedecz", label: "Przedecz, pow. kolski" },
  { value: "Gościno", label: "Gościno, pow. kołobrzeski" },
  { value: "Kołobrzeg", label: "Kołobrzeg, pow. kołobrzeski" },
  { value: "Końskie", label: "Końskie, pow. konecki" },
  { value: "Radoszyce", label: "Radoszyce, pow. konecki" },
  { value: "Stąporków", label: "Stąporków, pow. konecki" },
  { value: "Konin", label: "Konin" },
  { value: "Golina", label: "Golina, pow. koniński" },
  { value: "Kleczew", label: "Kleczew, pow. koniński" },
  { value: "Rychwał", label: "Rychwał, pow. koniński" },
  { value: "Sompolno", label: "Sompolno, pow. koniński" },
  { value: "Ślesin", label: "Ślesin, pow. koniński" },
  { value: "Koszalin", label: "Koszalin" },
  { value: "Bobolice", label: "Bobolice, pow. koszaliński" },
  { value: "Mielno", label: "Mielno, pow. koszaliński" },
  { value: "Polanów", label: "Polanów, pow. koszaliński" },
  { value: "Sianów", label: "Sianów, pow. koszaliński" },
  { value: "Czempiń", label: "Czempiń, pow. kościański" },
  { value: "Kościan", label: "Kościan, pow. kościański" },
  { value: "Krzywiń", label: "Krzywiń, pow. kościański" },
  { value: "Śmigiel", label: "Śmigiel, pow. kościański" },
  { value: "Kościerzyna", label: "Kościerzyna, pow. kościerski" },
  { value: "Kozienice", label: "Kozienice, pow. kozienicki" },
  { value: "Krzeszowice", label: "Krzeszowice, pow. krakowski" },
  { value: "Skała", label: "Skała, pow. krakowski" },
  { value: "Skawina", label: "Skawina, pow. krakowski" },
  { value: "Słomniki", label: "Słomniki, pow. krakowski" },
  { value: "Świątniki Górne", label: "Świątniki Górne, pow. krakowski" },
  { value: "Kraków", label: "Kraków" },
  { value: "Gogolin", label: "Gogolin, pow. krapkowicki" },
  { value: "Krapkowice", label: "Krapkowice, pow. krapkowicki" },
  { value: "Zdzieszowice", label: "Zdzieszowice, pow. krapkowicki" },
  { value: "Izbica", label: "Izbica, pow. krasnostawski" },
  { value: "Krasnystaw", label: "Krasnystaw, pow. krasnostawski" },
  { value: "Annopol", label: "Annopol, pow. kraśnicki" },
  { value: "Kraśnik", label: "Kraśnik, pow. kraśnicki" },
  { value: "Urzędów", label: "Urzędów, pow. kraśnicki" },
  { value: "Krosno", label: "Krosno" },
  { value: "Dukla", label: "Dukla, pow. krośnieński" },
  { value: "Gubin", label: "Gubin, pow. krośnieński" },
  { value: "Iwonicz-Zdrój", label: "Iwonicz-Zdrój, pow. krośnieński" },
  { value: "Jedlicze", label: "Jedlicze, pow. krośnieński" },
  { value: "Krosno Odrzańskie", label: "Krosno Odrzańskie, pow. krośnieński" },
  { value: "Rymanów", label: "Rymanów, pow. krośnieński" },
  { value: "Kobylin", label: "Kobylin, pow. krotoszyński" },
  {
    value: "Koźmin Wielkopolski",
    label: "Koźmin Wielkopolski, pow. krotoszyński",
  },
  { value: "Krotoszyn", label: "Krotoszyn, pow. krotoszyński" },
  { value: "Sulmierzyce", label: "Sulmierzyce, pow. krotoszyński" },
  { value: "Zduny", label: "Zduny, pow. krotoszyński" },
  { value: "Dąbrowice", label: "Dąbrowice, pow. kutnowski" },
  { value: "Krośniewice", label: "Krośniewice, pow. kutnowski" },
  { value: "Kutno", label: "Kutno, pow. kutnowski" },
  { value: "Żychlin", label: "Żychlin, pow. kutnowski" },
  { value: "Kwidzyn", label: "Kwidzyn, pow. kwidzyński" },
  { value: "Prabuty", label: "Prabuty, pow. kwidzyński" },
  { value: "Legionowo", label: "Legionowo, pow. legionowski" },
  { value: "Serock", label: "Serock, pow. legionowski" },
  { value: "Legnica", label: "Legnica" },
  { value: "Chojnów", label: "Chojnów, pow. legnicki" },
  { value: "Prochowice", label: "Prochowice, pow. legnicki" },
  { value: "Lesko", label: "Lesko, pow. leski" },
  { value: "Osieczna", label: "Osieczna, pow. leszczyński" },
  { value: "Rydzyna", label: "Rydzyna, pow. leszczyński" },
  { value: "Leszno", label: "Leszno" },
  { value: "Leżajsk", label: "Leżajsk, pow. leżajski" },
  { value: "Nowa Sarzyna", label: "Nowa Sarzyna, pow. leżajski" },
  { value: "Lębork", label: "Lębork, pow. lęborski" },
  { value: "Łeba", label: "Łeba, pow. lęborski" },
  { value: "Lidzbark Warmiński", label: "Lidzbark Warmiński, pow. lidzbarski" },
  { value: "Orneta", label: "Orneta, pow. lidzbarski" },
  { value: "Limanowa", label: "Limanowa, pow. limanowski" },
  { value: "Mszana Dolna", label: "Mszana Dolna, pow. limanowski" },
  { value: "Dobrzyń nad Wisłą", label: "Dobrzyń nad Wisłą, pow. lipnowski" },
  { value: "Lipno", label: "Lipno, pow. lipnowski" },
  { value: "Skępe", label: "Skępe, pow. lipnowski" },
  { value: "Lipsko", label: "Lipsko, pow. lipski" },
  { value: "Solec nad Wisłą", label: "Solec nad Wisłą, pow. lipski" },
  { value: "Cieszanów", label: "Cieszanów, pow. lubaczowski" },
  { value: "Lubaczów", label: "Lubaczów, pow. lubaczowski" },
  { value: "Narol", label: "Narol, pow. lubaczowski" },
  { value: "Oleszyce", label: "Oleszyce, pow. lubaczowski" },
  { value: "Leśna", label: "Leśna, pow. lubański" },
  { value: "Lubań", label: "Lubań, pow. lubański" },
  { value: "Olszyna", label: "Olszyna, pow. lubański" },
  { value: "Świeradów-Zdrój", label: "Świeradów-Zdrój, pow. lubański" },
  { value: "Kamionka", label: "Kamionka, pow. lubartowski" },
  { value: "Kock", label: "Kock, pow. lubartowski" },
  { value: "Lubartów", label: "Lubartów, pow. lubartowski" },
  { value: "Ostrów Lubelski", label: "Ostrów Lubelski, pow. lubartowski" },
  { value: "Bełżyce", label: "Bełżyce, pow. lubelski" },
  { value: "Bychawa", label: "Bychawa, pow. lubelski" },
  { value: "Lubin", label: "Lubin, pow. lubiński" },
  { value: "Ścinawa", label: "Ścinawa, pow. lubiński" },
  { value: "Lublin", label: "Lublin" },
  { value: "Lubliniec", label: "Lubliniec, pow. lubliniecki" },
  { value: "Woźniki", label: "Woźniki, pow. lubliniecki" },
  { value: "Gryfów Śląski", label: "Gryfów Śląski, pow. lwówecki" },
  { value: "Lubomierz", label: "Lubomierz, pow. lwówecki" },
  { value: "Lwówek Śląski", label: "Lwówek Śląski, pow. lwówecki" },
  { value: "Mirsk", label: "Mirsk, pow. lwówecki" },
  { value: "Wleń", label: "Wleń, pow. lwówecki" },
  { value: "Łańcut", label: "Łańcut, pow. łańcucki" },
  { value: "Łask", label: "Łask, pow. łaski" },
  { value: "Łęczyca", label: "Łęczyca, pow. łęczycki" },
  { value: "Piątek", label: "Piątek, pow. łęczycki" },
  { value: "Łęczna", label: "Łęczna, pow. łęczyński" },
  { value: "Dobra", label: "Dobra, pow. łobeski" },
  { value: "Łobez", label: "Łobez, pow. łobeski" },
  { value: "Resko", label: "Resko, pow. łobeski" },
  { value: "Węgorzyno", label: "Węgorzyno, pow. łobeski" },
  { value: "Łomża", label: "Łomża" },
  { value: "Jedwabne", label: "Jedwabne, pow. łomżyński" },
  { value: "Nowogród", label: "Nowogród, pow. łomżyński" },
  { value: "Łosice", label: "Łosice, pow. łosicki" },
  { value: "Łowicz", label: "Łowicz, pow. łowicki" },
  { value: "Koluszki", label: "Koluszki, pow. łódzki wschodni" },
  { value: "Rzgów", label: "Rzgów, pow. łódzki wschodni" },
  { value: "Tuszyn", label: "Tuszyn, pow. łódzki wschodni" },
  { value: "Łódź", label: "Łódź" },
  { value: "Łuków", label: "Łuków, pow. łukowski" },
  { value: "Stoczek Łukowski", label: "Stoczek Łukowski, pow. łukowski" },
  { value: "Maków Mazowiecki", label: "Maków Mazowiecki, pow. makowski" },
  { value: "Różan", label: "Różan, pow. makowski" },
  { value: "Malbork", label: "Malbork, pow. malborski" },
  { value: "Nowy Staw", label: "Nowy Staw, pow. malborski" },
  { value: "Książ Wielki", label: "Książ Wielki, pow. miechowski" },
  { value: "Miechów", label: "Miechów, pow. miechowski" },
  { value: "Mielec", label: "Mielec, pow. mielecki" },
  { value: "Przecław", label: "Przecław, pow. mielecki" },
  { value: "Radomyśl Wielki", label: "Radomyśl Wielki, pow. mielecki" },
  { value: "Międzychód", label: "Międzychód, pow. międzychodzki" },
  { value: "Sieraków", label: "Sieraków, pow. międzychodzki" },
  { value: "Międzyrzecz", label: "Międzyrzecz, pow. międzyrzecki" },
  { value: "Skwierzyna", label: "Skwierzyna, pow. międzyrzecki" },
  { value: "Trzciel", label: "Trzciel, pow. międzyrzecki" },
  { value: "Łaziska Górne", label: "Łaziska Górne, pow. mikołowski" },
  { value: "Mikołów", label: "Mikołów, pow. mikołowski" },
  { value: "Orzesze", label: "Orzesze, pow. mikołowski" },
  { value: "Milicz", label: "Milicz, pow. milicki" },
  { value: "Cegłów", label: "Cegłów, pow. miński" },
  { value: "Halinów", label: "Halinów, pow. miński" },
  { value: "Kałuszyn", label: "Kałuszyn, pow. miński" },
  { value: "Latowicz", label: "Latowicz, pow. miński" },
  { value: "Mińsk Mazowiecki", label: "Mińsk Mazowiecki, pow. miński" },
  { value: "Mrozy", label: "Mrozy, pow. miński" },
  { value: "Sulejówek", label: "Sulejówek, pow. miński" },
  { value: "Mława", label: "Mława, pow. mławski" },
  { value: "Mogilno", label: "Mogilno, pow. mogileński" },
  { value: "Strzelno", label: "Strzelno, pow. mogileński" },
  { value: "Goniądz", label: "Goniądz, pow. moniecki" },
  { value: "Knyszyn", label: "Knyszyn, pow. moniecki" },
  { value: "Mońki", label: "Mońki, pow. moniecki" },
  { value: "Mikołajki", label: "Mikołajki, pow. mrągowski" },
  { value: "Mrągowo", label: "Mrągowo, pow. mrągowski" },
  { value: "Mysłowice", label: "Mysłowice" },
  { value: "Koziegłowy", label: "Koziegłowy, pow. myszkowski" },
  { value: "Myszków", label: "Myszków, pow. myszkowski" },
  { value: "Żarki", label: "Żarki, pow. myszkowski" },
  { value: "Dobczyce", label: "Dobczyce, pow. myślenicki" },
  { value: "Myślenice", label: "Myślenice, pow. myślenicki" },
  { value: "Sułkowice", label: "Sułkowice, pow. myślenicki" },
  { value: "Barlinek", label: "Barlinek, pow. myśliborski" },
  { value: "Dębno", label: "Dębno, pow. myśliborski" },
  { value: "Myślibórz", label: "Myślibórz, pow. myśliborski" },
  { value: "Kcynia", label: "Kcynia, pow. nakielski" },
  { value: "Mrocza", label: "Mrocza, pow. nakielski" },
  { value: "Nakło nad Notecią", label: "Nakło nad Notecią, pow. nakielski" },
  { value: "Szubin", label: "Szubin, pow. nakielski" },
  { value: "Namysłów", label: "Namysłów, pow. namysłowski" },
  { value: "Nidzica", label: "Nidzica, pow. nidzicki" },
  { value: "Nisko", label: "Nisko, pow. niżański" },
  { value: "Rudnik nad Sanem", label: "Rudnik nad Sanem, pow. niżański" },
  { value: "Ulanów", label: "Ulanów, pow. niżański" },
  { value: "Krynica Morska", label: "Krynica Morska, pow. nowodworski" },
  { value: "Nasielsk", label: "Nasielsk, pow. nowodworski" },
  { value: "Nowy Dwór Gdański", label: "Nowy Dwór Gdański, pow. nowodworski" },
  {
    value: "Nowy Dwór Mazowiecki",
    label: "Nowy Dwór Mazowiecki, pow. nowodworski",
  },
  { value: "Zakroczym", label: "Zakroczym, pow. nowodworski" },
  {
    value: "Nowe Miasto Lubawskie",
    label: "Nowe Miasto Lubawskie, pow. nowomiejski",
  },
  { value: "Grybów", label: "Grybów, pow. nowosądecki" },
  { value: "Krynica-Zdrój", label: "Krynica-Zdrój, pow. nowosądecki" },
  { value: "Muszyna", label: "Muszyna, pow. nowosądecki" },
  { value: "Piwniczna-Zdrój", label: "Piwniczna-Zdrój, pow. nowosądecki" },
  { value: "Stary Sącz", label: "Stary Sącz, pow. nowosądecki" },
  { value: "Bytom Odrzański", label: "Bytom Odrzański, pow. nowosolski" },
  { value: "Kożuchów", label: "Kożuchów, pow. nowosolski" },
  { value: "Nowa Sól", label: "Nowa Sól, pow. nowosolski" },
  { value: "Nowe Miasteczko", label: "Nowe Miasteczko, pow. nowosolski" },
  { value: "Otyń", label: "Otyń, pow. nowosolski" },
  { value: "Czarny Dunajec", label: "Czarny Dunajec, pow. nowotarski" },
  { value: "Nowy Targ", label: "Nowy Targ, pow. nowotarski" },
  { value: "Rabka-Zdrój", label: "Rabka-Zdrój, pow. nowotarski" },
  { value: "Szczawnica", label: "Szczawnica, pow. nowotarski" },
  { value: "Lwówek", label: "Lwówek, pow. nowotomyski" },
  { value: "Nowy Tomyśl", label: "Nowy Tomyśl, pow. nowotomyski" },
  { value: "Opalenica", label: "Opalenica, pow. nowotomyski" },
  { value: "Zbąszyń", label: "Zbąszyń, pow. nowotomyski" },
  { value: "Nowy Sącz", label: "Nowy Sącz" },
  { value: "Głuchołazy", label: "Głuchołazy, pow. nyski" },
  { value: "Korfantów", label: "Korfantów, pow. nyski" },
  { value: "Nysa", label: "Nysa, pow. nyski" },
  { value: "Otmuchów", label: "Otmuchów, pow. nyski" },
  { value: "Paczków", label: "Paczków, pow. nyski" },
  { value: "Oborniki", label: "Oborniki, pow. obornicki" },
  { value: "Rogoźno", label: "Rogoźno, pow. obornicki" },
  { value: "Olecko", label: "Olecko, pow. olecki" },
  { value: "Dobrodzień", label: "Dobrodzień, pow. oleski" },
  { value: "Gorzów Śląski", label: "Gorzów Śląski, pow. oleski" },
  { value: "Olesno", label: "Olesno, pow. oleski" },
  { value: "Praszka", label: "Praszka, pow. oleski" },
  { value: "Bierutów", label: "Bierutów, pow. oleśnicki" },
  { value: "Międzybórz", label: "Międzybórz, pow. oleśnicki" },
  { value: "Oleśnica", label: "Oleśnica, pow. oleśnicki" },
  { value: "Syców", label: "Syców, pow. oleśnicki" },
  { value: "Twardogóra", label: "Twardogóra, pow. oleśnicki" },
  { value: "Bukowno", label: "Bukowno, pow. olkuski" },
  { value: "Olkusz", label: "Olkusz, pow. olkuski" },
  { value: "Wolbrom", label: "Wolbrom, pow. olkuski" },
  { value: "Olsztyn", label: "Olsztyn" },
  { value: "Barczewo", label: "Barczewo, pow. olsztyński" },
  { value: "Biskupiec", label: "Biskupiec, pow. olsztyński" },
  { value: "Dobre Miasto", label: "Dobre Miasto, pow. olsztyński" },
  { value: "Jeziorany", label: "Jeziorany, pow. olsztyński" },
  { value: "Olsztynek", label: "Olsztynek, pow. olsztyński" },
  { value: "Jelcz-Laskowice", label: "Jelcz-Laskowice, pow. oławski" },
  { value: "Oława", label: "Oława, pow. oławski" },
  { value: "Iwaniska", label: "Iwaniska, pow. opatowski" },
  { value: "Opatów", label: "Opatów, pow. opatowski" },
  { value: "Ożarów", label: "Ożarów, pow. opatowski" },
  { value: "Drzewica", label: "Drzewica, pow. opoczyński" },
  { value: "Opoczno", label: "Opoczno, pow. opoczyński" },
  { value: "Opole", label: "Opole" },
  { value: "Józefów nad Wisłą", label: "Józefów nad Wisłą, pow. opolski" },
  { value: "Niemodlin", label: "Niemodlin, pow. opolski" },
  { value: "Opole Lubelskie", label: "Opole Lubelskie, pow. opolski" },
  { value: "Ozimek", label: "Ozimek, pow. opolski" },
  { value: "Poniatowa", label: "Poniatowa, pow. opolski" },
  { value: "Prószków", label: "Prószków, pow. opolski" },
  { value: "Tułowice", label: "Tułowice, pow. opolski" },
  { value: "Myszyniec", label: "Myszyniec, pow. ostrołęcki" },
  { value: "Ostrołęka", label: "Ostrołęka" },
  { value: "Ćmielów", label: "Ćmielów, pow. ostrowiecki" },
  { value: "Kunów", label: "Kunów, pow. ostrowiecki" },
  {
    value: "Ostrowiec Świętokrzyski",
    label: "Ostrowiec Świętokrzyski, pow. ostrowiecki",
  },
  { value: "Brok", label: "Brok, pow. ostrowski" },
  { value: "Nowe Skalmierzyce", label: "Nowe Skalmierzyce, pow. ostrowski" },
  { value: "Odolanów", label: "Odolanów, pow. ostrowski" },
  { value: "Ostrów Mazowiecka", label: "Ostrów Mazowiecka, pow. ostrowski" },
  {
    value: "Ostrów Wielkopolski",
    label: "Ostrów Wielkopolski, pow. ostrowski",
  },
  { value: "Raszków", label: "Raszków, pow. ostrowski" },
  { value: "Miłakowo", label: "Miłakowo, pow. ostródzki" },
  { value: "Miłomłyn", label: "Miłomłyn, pow. ostródzki" },
  { value: "Morąg", label: "Morąg, pow. ostródzki" },
  { value: "Ostróda", label: "Ostróda, pow. ostródzki" },
  {
    value: "Grabów nad Prosną",
    label: "Grabów nad Prosną, pow. ostrzeszowski",
  },
  { value: "Mikstat", label: "Mikstat, pow. ostrzeszowski" },
  { value: "Ostrzeszów", label: "Ostrzeszów, pow. ostrzeszowski" },
  { value: "Brzeszcze", label: "Brzeszcze, pow. oświęcimski" },
  { value: "Chełmek", label: "Chełmek, pow. oświęcimski" },
  { value: "Kęty", label: "Kęty, pow. oświęcimski" },
  { value: "Oświęcim", label: "Oświęcim, pow. oświęcimski" },
  { value: "Zator", label: "Zator, pow. oświęcimski" },
  { value: "Józefów", label: "Józefów, pow. otwocki" },
  { value: "Karczew", label: "Karczew, pow. otwocki" },
  { value: "Otwock", label: "Otwock, pow. otwocki" },
  {
    value: "Konstantynów Łódzki",
    label: "Konstantynów Łódzki, pow. pabianicki",
  },
  { value: "Lutomiersk", label: "Lutomiersk, pow. pabianicki" },
  { value: "Pabianice", label: "Pabianice, pow. pabianicki" },
  { value: "Działoszyn", label: "Działoszyn, pow. pajęczański" },
  { value: "Pajęczno", label: "Pajęczno, pow. pajęczański" },
  { value: "Parczew", label: "Parczew, pow. parczewski" },
  { value: "Góra Kalwaria", label: "Góra Kalwaria, pow. piaseczyński" },
  {
    value: "Konstancin-Jeziorna",
    label: "Konstancin-Jeziorna, pow. piaseczyński",
  },
  { value: "Piaseczno", label: "Piaseczno, pow. piaseczyński" },
  { value: "Tarczyn", label: "Tarczyn, pow. piaseczyński" },
  { value: "Piekary Śląskie", label: "Piekary Śląskie" },
  { value: "Kaczory", label: "Kaczory, pow. pilski" },
  { value: "Łobżenica", label: "Łobżenica, pow. pilski" },
  {
    value: "Miasteczko Krajeńskie",
    label: "Miasteczko Krajeńskie, pow. pilski",
  },
  { value: "Piła", label: "Piła, pow. pilski" },
  { value: "Ujście", label: "Ujście, pow. pilski" },
  { value: "Wyrzysk", label: "Wyrzysk, pow. pilski" },
  { value: "Wysoka", label: "Wysoka, pow. pilski" },
  { value: "Działoszyce", label: "Działoszyce, pow. pińczowski" },
  { value: "Pińczów", label: "Pińczów, pow. pińczowski" },
  { value: "Rozprza", label: "Rozprza, pow. piotrkowski" },
  { value: "Sulejów", label: "Sulejów, pow. piotrkowski" },
  { value: "Wolbórz", label: "Wolbórz, pow. piotrkowski" },
  { value: "Piotrków Trybunalski", label: "Piotrków Trybunalski" },
  { value: "Biała Piska", label: "Biała Piska, pow. piski" },
  { value: "Orzysz", label: "Orzysz, pow. piski" },
  { value: "Pisz", label: "Pisz, pow. piski" },
  { value: "Ruciane-Nida", label: "Ruciane-Nida, pow. piski" },
  { value: "Chocz", label: "Chocz, pow. pleszewski" },
  { value: "Dobrzyca", label: "Dobrzyca, pow. pleszewski" },
  { value: "Pleszew", label: "Pleszew, pow. pleszewski" },
  { value: "Płock", label: "Płock" },
  { value: "Bodzanów", label: "Bodzanów, pow. płocki" },
  { value: "Drobin", label: "Drobin, pow. płocki" },
  { value: "Gąbin", label: "Gąbin, pow. płocki" },
  { value: "Wyszogród", label: "Wyszogród, pow. płocki" },
  { value: "Czerwińsk nad Wisłą", label: "Czerwińsk nad Wisłą, pow. płoński" },
  { value: "Nowe Miasto", label: "Nowe Miasto, pow. płoński" },
  { value: "Płońsk", label: "Płońsk, pow. płoński" },
  { value: "Raciąż", label: "Raciąż, pow. płoński" },
  { value: "Sochocin", label: "Sochocin, pow. płoński" },
  { value: "Poddębice", label: "Poddębice, pow. poddębicki" },
  { value: "Uniejów", label: "Uniejów, pow. poddębicki" },
  { value: "Nowe Warpno", label: "Nowe Warpno, pow. policki" },
  { value: "Police", label: "Police, pow. policki" },
  { value: "Chocianów", label: "Chocianów, pow. polkowicki" },
  { value: "Polkowice", label: "Polkowice, pow. polkowicki" },
  { value: "Przemków", label: "Przemków, pow. polkowicki" },
  { value: "Poznań", label: "Poznań" },
  { value: "Buk", label: "Buk, pow. poznański" },
  { value: "Kostrzyn", label: "Kostrzyn, pow. poznański" },
  { value: "Kórnik", label: "Kórnik, pow. poznański" },
  { value: "Luboń", label: "Luboń, pow. poznański" },
  { value: "Mosina", label: "Mosina, pow. poznański" },
  { value: "Murowana Goślina", label: "Murowana Goślina, pow. poznański" },
  { value: "Pobiedziska", label: "Pobiedziska, pow. poznański" },
  { value: "Puszczykowo", label: "Puszczykowo, pow. poznański" },
  { value: "Stęszew", label: "Stęszew, pow. poznański" },
  { value: "Swarzędz", label: "Swarzędz, pow. poznański" },
  { value: "Koszyce", label: "Koszyce, pow. proszowicki" },
  { value: "Nowe Brzesko", label: "Nowe Brzesko, pow. proszowicki" },
  { value: "Proszowice", label: "Proszowice, pow. proszowicki" },
  { value: "Biała", label: "Biała, pow. prudnicki" },
  { value: "Głogówek", label: "Głogówek, pow. prudnicki" },
  { value: "Prudnik", label: "Prudnik, pow. prudnicki" },
  { value: "Brwinów", label: "Brwinów, pow. pruszkowski" },
  { value: "Piastów", label: "Piastów, pow. pruszkowski" },
  { value: "Pruszków", label: "Pruszków, pow. pruszkowski" },
  { value: "Chorzele", label: "Chorzele, pow. przasnyski" },
  { value: "Przasnysz", label: "Przasnysz, pow. przasnyski" },
  { value: "Dubiecko", label: "Dubiecko, pow. przemyski" },
  { value: "Przemyśl", label: "Przemyśl" },
  { value: "Kańczuga", label: "Kańczuga, pow. przeworski" },
  { value: "Przeworsk", label: "Przeworsk, pow. przeworski" },
  { value: "Sieniawa", label: "Sieniawa, pow. przeworski" },
  { value: "Przysucha", label: "Przysucha, pow. przysuski" },
  { value: "Pszczyna", label: "Pszczyna, pow. pszczyński" },
  { value: "Hel", label: "Hel, pow. pucki" },
  { value: "Jastarnia", label: "Jastarnia, pow. pucki" },
  { value: "Puck", label: "Puck, pow. pucki" },
  { value: "Władysławowo", label: "Władysławowo, pow. pucki" },
  { value: "Kazimierz Dolny", label: "Kazimierz Dolny, pow. puławski" },
  { value: "Nałęczów", label: "Nałęczów, pow. puławski" },
  { value: "Puławy", label: "Puławy, pow. puławski" },
  { value: "Pułtusk", label: "Pułtusk, pow. pułtuski" },
  { value: "Lipiany", label: "Lipiany, pow. pyrzycki" },
  { value: "Pyrzyce", label: "Pyrzyce, pow. pyrzycki" },
  { value: "Krzanowice", label: "Krzanowice, pow. raciborski" },
  { value: "Kuźnia Raciborska", label: "Kuźnia Raciborska, pow. raciborski" },
  { value: "Racibórz", label: "Racibórz, pow. raciborski" },
  { value: "Radom", label: "Radom" },
  { value: "Iłża", label: "Iłża, pow. radomski" },
  { value: "Jedlnia-Letnisko", label: "Jedlnia-Letnisko, pow. radomski" },
  { value: "Pionki", label: "Pionki, pow. radomski" },
  { value: "Skaryszew", label: "Skaryszew, pow. radomski" },
  { value: "Kamieńsk", label: "Kamieńsk, pow. radomszczański" },
  { value: "Przedbórz", label: "Przedbórz, pow. radomszczański" },
  { value: "Radomsko", label: "Radomsko, pow. radomszczański" },
  { value: "Piotrków Kujawski", label: "Piotrków Kujawski, pow. radziejowski" },
  { value: "Radziejów", label: "Radziejów, pow. radziejowski" },
  { value: "Radzyń Podlaski", label: "Radzyń Podlaski, pow. radzyński" },
  { value: "Bojanowo", label: "Bojanowo, pow. rawicki" },
  { value: "Jutrosin", label: "Jutrosin, pow. rawicki" },
  { value: "Miejska Górka", label: "Miejska Górka, pow. rawicki" },
  { value: "Rawicz", label: "Rawicz, pow. rawicki" },
  { value: "Biała Rawska", label: "Biała Rawska, pow. rawski" },
  { value: "Rawa Mazowiecka", label: "Rawa Mazowiecka, pow. rawski" },
  { value: "Ropczyce", label: "Ropczyce, pow. ropczycko-sędziszowski" },
  {
    value: "Sędziszów Małopolski",
    label: "Sędziszów Małopolski, pow. ropczycko-sędziszowski",
  },
  { value: "Ruda Śląska", label: "Ruda Śląska" },
  {
    value: "Czerwionka-Leszczyny",
    label: "Czerwionka-Leszczyny, pow. rybnicki",
  },
  { value: "Rybnik", label: "Rybnik" },
  { value: "Dęblin", label: "Dęblin, pow. rycki" },
  { value: "Ryki", label: "Ryki, pow. rycki" },
  { value: "Rypin", label: "Rypin, pow. rypiński" },
  { value: "Błażowa", label: "Błażowa, pow. rzeszowski" },
  { value: "Boguchwała", label: "Boguchwała, pow. rzeszowski" },
  { value: "Dynów", label: "Dynów, pow. rzeszowski" },
  { value: "Głogów Małopolski", label: "Głogów Małopolski, pow. rzeszowski" },
  { value: "Sokołów Małopolski", label: "Sokołów Małopolski, pow. rzeszowski" },
  { value: "Tyczyn", label: "Tyczyn, pow. rzeszowski" },
  { value: "Rzeszów", label: "Rzeszów" },
  { value: "Klimontów", label: "Klimontów, pow. sandomierski" },
  { value: "Koprzywnica", label: "Koprzywnica, pow. sandomierski" },
  { value: "Sandomierz", label: "Sandomierz, pow. sandomierski" },
  { value: "Zawichost", label: "Zawichost, pow. sandomierski" },
  { value: "Sanok", label: "Sanok, pow. sanocki" },
  { value: "Zagórz", label: "Zagórz, pow. sanocki" },
  { value: "Sejny", label: "Sejny, pow. sejneński" },
  { value: "Kamień Krajeński", label: "Kamień Krajeński, pow. sępoleński" },
  { value: "Sępólno Krajeńskie", label: "Sępólno Krajeńskie, pow. sępoleński" },
  { value: "Więcbork", label: "Więcbork, pow. sępoleński" },
  { value: "Siedlce", label: "Siedlce" },
  { value: "Mordy", label: "Mordy, pow. siedlecki" },
  { value: "Siemianowice Śląskie", label: "Siemianowice Śląskie" },
  { value: "Drohiczyn", label: "Drohiczyn, pow. siemiatycki" },
  { value: "Siemiatycze", label: "Siemiatycze, pow. siemiatycki" },
  { value: "Błaszki", label: "Błaszki, pow. sieradzki" },
  { value: "Sieradz", label: "Sieradz, pow. sieradzki" },
  { value: "Warta", label: "Warta, pow. sieradzki" },
  { value: "Złoczew", label: "Złoczew, pow. sieradzki" },
  { value: "Sierpc", label: "Sierpc, pow. sierpecki" },
  { value: "Skarżysko-Kamienna", label: "Skarżysko-Kamienna, pow. skarżyski" },
  { value: "Suchedniów", label: "Suchedniów, pow. skarżyski" },
  { value: "Skierniewice", label: "Skierniewice" },
  { value: "Bolimów", label: "Bolimów, pow. skierniewicki" },
  { value: "Darłowo", label: "Darłowo, pow. sławieński" },
  { value: "Sławno", label: "Sławno, pow. sławieński" },
  { value: "Cybinka", label: "Cybinka, pow. słubicki" },
  { value: "Ośno Lubuskie", label: "Ośno Lubuskie, pow. słubicki" },
  { value: "Rzepin", label: "Rzepin, pow. słubicki" },
  { value: "Słubice", label: "Słubice, pow. słubicki" },
  { value: "Słupca", label: "Słupca, pow. słupecki" },
  { value: "Zagórów", label: "Zagórów, pow. słupecki" },
  { value: "Słupsk", label: "Słupsk" },
  { value: "Kępice", label: "Kępice, pow. słupski" },
  { value: "Ustka", label: "Ustka, pow. słupski" },
  { value: "Sochaczew", label: "Sochaczew, pow. sochaczewski" },
  { value: "Kosów Lacki", label: "Kosów Lacki, pow. sokołowski" },
  { value: "Sokołów Podlaski", label: "Sokołów Podlaski, pow. sokołowski" },
  { value: "Dąbrowa Białostocka", label: "Dąbrowa Białostocka, pow. sokólski" },
  { value: "Krynki", label: "Krynki, pow. sokólski" },
  { value: "Sokółka", label: "Sokółka, pow. sokólski" },
  { value: "Suchowola", label: "Suchowola, pow. sokólski" },
  { value: "Sopot", label: "Sopot" },
  { value: "Sosnowiec", label: "Sosnowiec" },
  { value: "Stalowa Wola", label: "Stalowa Wola, pow. stalowowolski" },
  { value: "Zaklików", label: "Zaklików, pow. stalowowolski" },
  { value: "Starachowice", label: "Starachowice, pow. starachowicki" },
  { value: "Wąchock", label: "Wąchock, pow. starachowicki" },
  { value: "Chociwel", label: "Chociwel, pow. stargardzki" },
  { value: "Dobrzany", label: "Dobrzany, pow. stargardzki" },
  { value: "Ińsko", label: "Ińsko, pow. stargardzki" },
  { value: "Stargard", label: "Stargard, pow. stargardzki" },
  { value: "Suchań", label: "Suchań, pow. stargardzki" },
  { value: "Czarna Woda", label: "Czarna Woda, pow. starogardzki" },
  { value: "Skarszewy", label: "Skarszewy, pow. starogardzki" },
  { value: "Skórcz", label: "Skórcz, pow. starogardzki" },
  { value: "Starogard Gdański", label: "Starogard Gdański, pow. starogardzki" },
  { value: "Oleśnica", label: "Oleśnica, pow. staszowski" },
  { value: "Osiek", label: "Osiek, pow. staszowski" },
  { value: "Połaniec", label: "Połaniec, pow. staszowski" },
  { value: "Staszów", label: "Staszów, pow. staszowski" },
  { value: "Szydłów", label: "Szydłów, pow. staszowski" },
  { value: "Kolonowskie", label: "Kolonowskie, pow. strzelecki" },
  { value: "Leśnica", label: "Leśnica, pow. strzelecki" },
  { value: "Strzelce Opolskie", label: "Strzelce Opolskie, pow. strzelecki" },
  { value: "Ujazd", label: "Ujazd, pow. strzelecki" },
  { value: "Zawadzkie", label: "Zawadzkie, pow. strzelecki" },
  { value: "Dobiegniew", label: "Dobiegniew, pow. strzelecko-drezdenecki" },
  { value: "Drezdenko", label: "Drezdenko, pow. strzelecko-drezdenecki" },
  {
    value: "Strzelce Krajeńskie",
    label: "Strzelce Krajeńskie, pow. strzelecko-drezdenecki",
  },
  { value: "Strzelin", label: "Strzelin, pow. strzeliński" },
  { value: "Wiązów", label: "Wiązów, pow. strzeliński" },
  { value: "Strzyżów", label: "Strzyżów, pow. strzyżowski" },
  { value: "Lubniewice", label: "Lubniewice, pow. sulęciński" },
  { value: "Sulęcin", label: "Sulęcin, pow. sulęciński" },
  { value: "Torzym", label: "Torzym, pow. sulęciński" },
  { value: "Jordanów", label: "Jordanów, pow. suski" },
  { value: "Maków Podhalański", label: "Maków Podhalański, pow. suski" },
  { value: "Sucha Beskidzka", label: "Sucha Beskidzka, pow. suski" },
  { value: "Suwałki", label: "Suwałki" },
  { value: "Obrzycko", label: "Obrzycko, pow. szamotulski" },
  { value: "Ostroróg", label: "Ostroróg, pow. szamotulski" },
  { value: "Pniewy", label: "Pniewy, pow. szamotulski" },
  { value: "Szamotuły", label: "Szamotuły, pow. szamotulski" },
  { value: "Wronki", label: "Wronki, pow. szamotulski" },
  { value: "Szczecin", label: "Szczecin" },
  { value: "Barwice", label: "Barwice, pow. szczecinecki" },
  { value: "Biały Bór", label: "Biały Bór, pow. szczecinecki" },
  { value: "Borne Sulinowo", label: "Borne Sulinowo, pow. szczecinecki" },
  { value: "Szczecinek", label: "Szczecinek, pow. szczecinecki" },
  { value: "Pasym", label: "Pasym, pow. szczycieński" },
  { value: "Szczytno", label: "Szczytno, pow. szczycieński" },
  { value: "Wielbark", label: "Wielbark, pow. szczycieński" },
  { value: "Dzierzgoń", label: "Dzierzgoń, pow. sztumski" },
  { value: "Sztum", label: "Sztum, pow. sztumski" },
  { value: "Jastrząb", label: "Jastrząb, pow. szydłowiecki" },
  { value: "Szydłowiec", label: "Szydłowiec, pow. szydłowiecki" },
  { value: "Miękinia", label: "Miękinia, pow. średzki" },
  { value: "Środa Śląska", label: "Środa Śląska, pow. średzki" },
  { value: "Środa Wielkopolska", label: "Środa Wielkopolska, pow. średzki" },
  { value: "Dolsk", label: "Dolsk, pow. śremski" },
  { value: "Książ Wielkopolski", label: "Książ Wielkopolski, pow. śremski" },
  { value: "Śrem", label: "Śrem, pow. śremski" },
  { value: "Jaworzyna Śląska", label: "Jaworzyna Śląska, pow. świdnicki" },
  { value: "Piaski", label: "Piaski, pow. świdnicki" },
  { value: "Strzegom", label: "Strzegom, pow. świdnicki" },
  { value: "Świdnica", label: "Świdnica, pow. świdnicki" },
  { value: "Świdnik", label: "Świdnik, pow. świdnicki" },
  { value: "Świebodzice", label: "Świebodzice, pow. świdnicki" },
  { value: "Żarów", label: "Żarów, pow. świdnicki" },
  { value: "Połczyn-Zdrój", label: "Połczyn-Zdrój, pow. świdwiński" },
  { value: "Świdwin", label: "Świdwin, pow. świdwiński" },
  { value: "Świebodzin", label: "Świebodzin, pow. świebodziński" },
  { value: "Zbąszynek", label: "Zbąszynek, pow. świebodziński" },
  { value: "Nowe", label: "Nowe, pow. świecki" },
  { value: "Pruszcz", label: "Pruszcz, pow. świecki" },
  { value: "Świecie", label: "Świecie, pow. świecki" },
  { value: "Świętochłowice", label: "Świętochłowice" },
  { value: "Świnoujście", label: "Świnoujście" },
  { value: "Tarnobrzeg", label: "Tarnobrzeg" },
  {
    value: "Baranów Sandomierski",
    label: "Baranów Sandomierski, pow. tarnobrzeski",
  },
  { value: "Nowa Dęba", label: "Nowa Dęba, pow. tarnobrzeski" },
  { value: "Kalety", label: "Kalety, pow. tarnogórski" },
  {
    value: "Miasteczko Śląskie",
    label: "Miasteczko Śląskie, pow. tarnogórski",
  },
  { value: "Radzionków", label: "Radzionków, pow. tarnogórski" },
  { value: "Tarnowskie Góry", label: "Tarnowskie Góry, pow. tarnogórski" },
  { value: "Ciężkowice", label: "Ciężkowice, pow. tarnowski" },
  { value: "Radłów", label: "Radłów, pow. tarnowski" },
  { value: "Ryglice", label: "Ryglice, pow. tarnowski" },
  { value: "Tuchów", label: "Tuchów, pow. tarnowski" },
  { value: "Wojnicz", label: "Wojnicz, pow. tarnowski" },
  { value: "Zakliczyn", label: "Zakliczyn, pow. tarnowski" },
  { value: "Żabno", label: "Żabno, pow. tarnowski" },
  { value: "Tarnów", label: "Tarnów" },
  { value: "Zakopane", label: "Zakopane, pow. tatrzański" },
  { value: "Gniew", label: "Gniew, pow. tczewski" },
  { value: "Pelplin", label: "Pelplin, pow. tczewski" },
  { value: "Tczew", label: "Tczew, pow. tczewski" },
  { value: "Lubycza Królewska", label: "Lubycza Królewska, pow. tomaszowski" },
  { value: "Łaszczów", label: "Łaszczów, pow. tomaszowski" },
  { value: "Tomaszów Lubelski", label: "Tomaszów Lubelski, pow. tomaszowski" },
  {
    value: "Tomaszów Mazowiecki",
    label: "Tomaszów Mazowiecki, pow. tomaszowski",
  },
  { value: "Tyszowce", label: "Tyszowce, pow. tomaszowski" },
  { value: "Ujazd", label: "Ujazd, pow. tomaszowski" },
  { value: "Toruń", label: "Toruń" },
  { value: "Chełmża", label: "Chełmża, pow. toruński" },
  { value: "Oborniki Śląskie", label: "Oborniki Śląskie, pow. trzebnicki" },
  { value: "Prusice", label: "Prusice, pow. trzebnicki" },
  { value: "Trzebnica", label: "Trzebnica, pow. trzebnicki" },
  { value: "Żmigród", label: "Żmigród, pow. trzebnicki" },
  { value: "Tuchola", label: "Tuchola, pow. tucholski" },
  { value: "Dobra", label: "Dobra, pow. turecki" },
  { value: "Tuliszków", label: "Tuliszków, pow. turecki" },
  { value: "Turek", label: "Turek, pow. turecki" },
  { value: "Tychy", label: "Tychy" },
  { value: "Andrychów", label: "Andrychów, pow. wadowicki" },
  {
    value: "Kalwaria Zebrzydowska",
    label: "Kalwaria Zebrzydowska, pow. wadowicki",
  },
  { value: "Wadowice", label: "Wadowice, pow. wadowicki" },
  { value: "Wałbrzych", label: "Wałbrzych" },
  { value: "Boguszów-Gorce", label: "Boguszów-Gorce, pow. wałbrzyski" },
  { value: "Głuszyca", label: "Głuszyca, pow. wałbrzyski" },
  { value: "Jedlina-Zdrój", label: "Jedlina-Zdrój, pow. wałbrzyski" },
  { value: "Mieroszów", label: "Mieroszów, pow. wałbrzyski" },
  { value: "Szczawno-Zdrój", label: "Szczawno-Zdrój, pow. wałbrzyski" },
  { value: "Człopa", label: "Człopa, pow. wałecki" },
  { value: "Mirosławiec", label: "Mirosławiec, pow. wałecki" },
  { value: "Tuczno", label: "Tuczno, pow. wałecki" },
  { value: "Wałcz", label: "Wałcz, pow. wałecki" },
  { value: "Błonie", label: "Błonie, pow. warszawski zachodni" },
  { value: "Łomianki", label: "Łomianki, pow. warszawski zachodni" },
  {
    value: "Ożarów Mazowiecki",
    label: "Ożarów Mazowiecki, pow. warszawski zachodni",
  },
  { value: "Wąbrzeźno", label: "Wąbrzeźno, pow. wąbrzeski" },
  { value: "Gołańcz", label: "Gołańcz, pow. wągrowiecki" },
  { value: "Skoki", label: "Skoki, pow. wągrowiecki" },
  { value: "Wągrowiec", label: "Wągrowiec, pow. wągrowiecki" },
  { value: "Reda", label: "Reda, pow. wejherowski" },
  { value: "Rumia", label: "Rumia, pow. wejherowski" },
  { value: "Wejherowo", label: "Wejherowo, pow. wejherowski" },
  { value: "Węgorzewo", label: "Węgorzewo, pow. węgorzewski" },
  { value: "Łochów", label: "Łochów, pow. węgrowski" },
  { value: "Węgrów", label: "Węgrów, pow. węgrowski" },
  { value: "Niepołomice", label: "Niepołomice, pow. wielicki" },
  { value: "Wieliczka", label: "Wieliczka, pow. wielicki" },
  { value: "Wieluń", label: "Wieluń, pow. wieluński" },
  { value: "Lututów", label: "Lututów, pow. wieruszowski" },
  { value: "Wieruszów", label: "Wieruszów, pow. wieruszowski" },
  { value: "Włocławek", label: "Włocławek" },
  { value: "Brześć Kujawski", label: "Brześć Kujawski, pow. włocławski" },
  { value: "Chodecz", label: "Chodecz, pow. włocławski" },
  { value: "Izbica Kujawska", label: "Izbica Kujawska, pow. włocławski" },
  { value: "Kowal", label: "Kowal, pow. włocławski" },
  { value: "Lubień Kujawski", label: "Lubień Kujawski, pow. włocławski" },
  { value: "Lubraniec", label: "Lubraniec, pow. włocławski" },
  { value: "Włodawa", label: "Włodawa, pow. włodawski" },
  { value: "Włoszczowa", label: "Włoszczowa, pow. włoszczowski" },
  { value: "Pszów", label: "Pszów, pow. wodzisławski" },
  { value: "Radlin", label: "Radlin, pow. wodzisławski" },
  { value: "Rydułtowy", label: "Rydułtowy, pow. wodzisławski" },
  { value: "Wodzisław Śląski", label: "Wodzisław Śląski, pow. wodzisławski" },
  { value: "Wolsztyn", label: "Wolsztyn, pow. wolsztyński" },
  { value: "Jadów", label: "Jadów, pow. wołomiński" },
  { value: "Kobyłka", label: "Kobyłka, pow. wołomiński" },
  { value: "Marki", label: "Marki, pow. wołomiński" },
  { value: "Radzymin", label: "Radzymin, pow. wołomiński" },
  { value: "Tłuszcz", label: "Tłuszcz, pow. wołomiński" },
  { value: "Wołomin", label: "Wołomin, pow. wołomiński" },
  { value: "Ząbki", label: "Ząbki, pow. wołomiński" },
  { value: "Zielonka", label: "Zielonka, pow. wołomiński" },
  { value: "Brzeg Dolny", label: "Brzeg Dolny, pow. wołowski" },
  { value: "Wołów", label: "Wołów, pow. wołowski" },
  { value: "Wrocław", label: "Wrocław" },
  { value: "Kąty Wrocławskie", label: "Kąty Wrocławskie, pow. wrocławski" },
  { value: "Siechnice", label: "Siechnice, pow. wrocławski" },
  { value: "Sobótka", label: "Sobótka, pow. wrocławski" },
  { value: "Miłosław", label: "Miłosław, pow. wrzesiński" },
  { value: "Nekla", label: "Nekla, pow. wrzesiński" },
  { value: "Pyzdry", label: "Pyzdry, pow. wrzesiński" },
  { value: "Września", label: "Września, pow. wrzesiński" },
  { value: "Sława", label: "Sława, pow. wschowski" },
  { value: "Szlichtyngowa", label: "Szlichtyngowa, pow. wschowski" },
  { value: "Wschowa", label: "Wschowa, pow. wschowski" },
  { value: "Ciechanowiec", label: "Ciechanowiec, pow. wysokomazowiecki" },
  { value: "Czyżew", label: "Czyżew, pow. wysokomazowiecki" },
  { value: "Szepietowo", label: "Szepietowo, pow. wysokomazowiecki" },
  {
    value: "Wysokie Mazowieckie",
    label: "Wysokie Mazowieckie, pow. wysokomazowiecki",
  },
  { value: "Wyszków", label: "Wyszków, pow. wyszkowski" },
  { value: "Zabrze", label: "Zabrze" },
  { value: "Zambrów", label: "Zambrów, pow. zambrowski" },
  { value: "Krasnobród", label: "Krasnobród, pow. zamojski" },
  { value: "Szczebrzeszyn", label: "Szczebrzeszyn, pow. zamojski" },
  { value: "Zwierzyniec", label: "Zwierzyniec, pow. zamojski" },
  { value: "Zamość", label: "Zamość" },
  { value: "Łazy", label: "Łazy, pow. zawierciański" },
  { value: "Ogrodzieniec", label: "Ogrodzieniec, pow. zawierciański" },
  { value: "Pilica", label: "Pilica, pow. zawierciański" },
  { value: "Poręba", label: "Poręba, pow. zawierciański" },
  { value: "Szczekociny", label: "Szczekociny, pow. zawierciański" },
  { value: "Włodowice", label: "Włodowice, pow. zawierciański" },
  { value: "Zawiercie", label: "Zawiercie, pow. zawierciański" },
  { value: "Bardo", label: "Bardo, pow. ząbkowicki" },
  {
    value: "Kamieniec Ząbkowicki",
    label: "Kamieniec Ząbkowicki, pow. ząbkowicki",
  },
  { value: "Ząbkowice Śląskie", label: "Ząbkowice Śląskie, pow. ząbkowicki" },
  { value: "Ziębice", label: "Ziębice, pow. ząbkowicki" },
  { value: "Złoty Stok", label: "Złoty Stok, pow. ząbkowicki" },
  { value: "Szadek", label: "Szadek, pow. zduńskowolski" },
  { value: "Zduńska Wola", label: "Zduńska Wola, pow. zduńskowolski" },
  { value: "Aleksandrów Łódzki", label: "Aleksandrów Łódzki, pow. zgierski" },
  { value: "Głowno", label: "Głowno, pow. zgierski" },
  { value: "Ozorków", label: "Ozorków, pow. zgierski" },
  { value: "Stryków", label: "Stryków, pow. zgierski" },
  { value: "Zgierz", label: "Zgierz, pow. zgierski" },
  { value: "Bogatynia", label: "Bogatynia, pow. zgorzelecki" },
  { value: "Pieńsk", label: "Pieńsk, pow. zgorzelecki" },
  { value: "Węgliniec", label: "Węgliniec, pow. zgorzelecki" },
  { value: "Zawidów", label: "Zawidów, pow. zgorzelecki" },
  { value: "Zgorzelec", label: "Zgorzelec, pow. zgorzelecki" },
  { value: "Zielona Góra", label: "Zielona Góra" },
  { value: "Babimost", label: "Babimost, pow. zielonogórski" },
  { value: "Czerwieńsk", label: "Czerwieńsk, pow. zielonogórski" },
  { value: "Kargowa", label: "Kargowa, pow. zielonogórski" },
  {
    value: "Nowogród Bobrzański",
    label: "Nowogród Bobrzański, pow. zielonogórski",
  },
  { value: "Sulechów", label: "Sulechów, pow. zielonogórski" },
  { value: "Świerzawa", label: "Świerzawa, pow. złotoryjski" },
  { value: "Wojcieszów", label: "Wojcieszów, pow. złotoryjski" },
  { value: "Złotoryja", label: "Złotoryja, pow. złotoryjski" },
  { value: "Jastrowie", label: "Jastrowie, pow. złotowski" },
  { value: "Krajenka", label: "Krajenka, pow. złotowski" },
  { value: "Okonek", label: "Okonek, pow. złotowski" },
  { value: "Złotów", label: "Złotów, pow. złotowski" },
  { value: "Zwoleń", label: "Zwoleń, pow. zwoleński" },
  { value: "Gozdnica", label: "Gozdnica, pow. żagański" },
  { value: "Iłowa", label: "Iłowa, pow. żagański" },
  { value: "Małomice", label: "Małomice, pow. żagański" },
  { value: "Szprotawa", label: "Szprotawa, pow. żagański" },
  { value: "Żagań", label: "Żagań, pow. żagański" },
  { value: "Jasień", label: "Jasień, pow. żarski" },
  { value: "Lubsko", label: "Lubsko, pow. żarski" },
  { value: "Łęknica", label: "Łęknica, pow. żarski" },
  { value: "Żary", label: "Żary, pow. żarski" },
  { value: "Barcin", label: "Barcin, pow. żniński" },
  {
    value: "Janowiec Wielkopolski",
    label: "Janowiec Wielkopolski, pow. żniński",
  },
  { value: "Łabiszyn", label: "Łabiszyn, pow. żniński" },
  { value: "Żnin", label: "Żnin, pow. żniński" },
  { value: "Żory", label: "Żory" },
  { value: "Bieżuń", label: "Bieżuń, pow. żuromiński" },
  { value: "Lubowidz", label: "Lubowidz, pow. żuromiński" },
  { value: "Żuromin", label: "Żuromin, pow. żuromiński" },
  { value: "Mszczonów", label: "Mszczonów, pow. żyrardowski" },
  { value: "Wiskitki", label: "Wiskitki, pow. żyrardowski" },
  { value: "Żyrardów", label: "Żyrardów, pow. żyrardowski" },
  { value: "Żywiec", label: "Żywiec, pow. żywiecki" },
  { value: "Warszawa", label: "Warszawa" },
];

export default cities;
