import "./globals.css";

import { Lexend_Deca } from "next/font/google";
import React from "react";

import { NavigationMobile } from "@/components/navigation-mobile";
import { ScrollToTop } from "@/components/scroll-to-top";
import { cn } from "@/lib/utils";

import Providers from "./providers";

import type { Metadata } from "next";
const baseFont = Lexend_Deca({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Tickets App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body
        className={cn(
          `min-h-screen bg-background font-sans antialiased ${baseFont.variable}`,
        )}
      >
        <Providers>
          {children}
          <NavigationMobile />
        </Providers>
        <ScrollToTop />
      </body>
    </html>
  );
}
